# Generated by Django 3.2 on 2021-04-26 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 26, 20, 8, 9, 188644)),
        ),
    ]
