# Generated by Django 3.2 on 2021-04-26 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 26, 20, 36, 39, 152738, tzinfo=utc)),
        ),
    ]
